name: pandas-workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=0.24
  - jupyterlab=1.2
  - xlrd
  - xlsxwriter
  - dask
  - seaborn
  - pyarrow
  - fastparquet
  - bokeh
  - nodejs
  - python=3.7
